In [3]:
import numpy as np

In [4]:
l=[1,2,3,4]

In [5]:
a=np.asarray(l)
a

array([1, 2, 3, 4])

In [6]:
type(a)

numpy.ndarray

In [7]:
a.size #Total no of elements

4

In [8]:
a.shape

(4,)

In [9]:
a.ndim

1

In [12]:
a.itemsize # each element has 8 but size

8

In [14]:
id(a) # Memory of a

4568999472

In [16]:
hex(id(a))

'0x110556630'

In [17]:
a

array([1, 2, 3, 4])

In [18]:
a

array([1, 2, 3, 4])

In [20]:
a.dtype

dtype('int64')

In [23]:
a1 = np.array([34,56],dtype=float)

In [22]:
a1

array([34., 56.])